#!/usr/bin/env python3
"""
Parse the Claude Code session JSONL and produce chat/index.md:
  - Every real user prompt
  - Mapped to the nearest git commit SHA by timestamp
  - Output as markdown table and LaTeX table (for paper/report.tex)

Usage:
    python scripts/chat_index.py
    python scripts/chat_index.py --latex-out paper/chat_index.tex
"""

import json
import re
import subprocess
import sys
from pathlib import Path

REPO     = Path(__file__).parent.parent
CHAT_DIR = REPO / "chat"
JSONL    = Path.home() / ".claude/projects/-Users-nialloleary" \
           / "f23f85b0-55e2-40c3-aa23-a66a258f1d9c.jsonl"

SKIP_PREFIXES = (
    "{", "<local-command", "<command-name", "<bash-input",
    "<bash-stdout", "<bash-stderr", "<local-command-stdout",
)

# Prompts that drove actual code commits (hand-curated subset)
KEY_PROMPTS = {
    "are we connected to gh",
    "clone and track",
    "does it show steps on ProteinGym",
    "any assays related to parkinsons",
    "what is DMS",
    "what is the end goal",
    "how can foundation models like esm help",
    "download whatever you can",
    "any novel benchmark",
    "smoke test",
    "pls push",
    "pls add mac results",
    "make sure this is append only",
    "kick me off",
    "pull my results",
    "what is the wall",
    "open the hf model card",
    "append only story",
    "exact commands and executive order",
    "add all our method",
    "gitinclude the exported chat",
}


def git(*args) -> str:
    return subprocess.check_output(["git"] + list(args), cwd=REPO, text=True).strip()


def load_commits() -> list[dict]:
    raw = git("log", "--reverse", "--format=%H|%h|%ai|%s")
    out = []
    for line in raw.strip().splitlines():
        sha, short, ts, msg = line.split("|", 3)
        if msg.startswith("[story]"):
            continue
        out.append({"sha": sha, "short": short, "ts": ts[:19], "msg": msg})
    return out


def load_prompts() -> list[dict]:
    if not JSONL.exists():
        return []
    prompts = []
    with open(JSONL) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            if obj.get("type") != "user":
                continue
            msg = obj.get("message", {})
            if not isinstance(msg, dict) or msg.get("role") != "user":
                continue
            content = msg.get("content", "")
            if isinstance(content, list):
                text_parts = [
                    b.get("text", "") for b in content
                    if isinstance(b, dict) and b.get("type") == "text"
                ]
                text = " ".join(text_parts).strip()
            else:
                text = str(content).strip()

            if not text or len(text) < 4:
                continue
            if any(text.startswith(p) for p in SKIP_PREFIXES):
                continue
            # strip XML-like tags
            text = re.sub(r"<[^>]+>", "", text).strip()
            if not text or len(text) < 4:
                continue

            ts = obj.get("timestamp", "")[:19]
            prompts.append({"ts": ts, "text": text, "uuid": obj.get("uuid", "")})
    return prompts


def map_to_commits(prompts: list[dict], commits: list[dict]) -> list[dict]:
    """Map each prompt to the commit with the nearest timestamp >= prompt ts."""
    result = []
    for p in prompts:
        best = None
        for c in commits:
            if c["ts"] >= p["ts"]:
                best = c
                break
        if best is None and commits:
            best = commits[-1]
        result.append({**p, "commit": best})
    return result


def escape_md(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ").replace("\r", "")


def escape_tex(s: str) -> str:
    for ch, rep in [
        ("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"),
        ("$", r"\$"), ("#", r"\#"), ("_", r"\_"), ("{", r"\{"),
        ("}", r"\}"), ("~", r"\textasciitilde{}"), ("^", r"\^{}"),
    ]:
        s = s.replace(ch, rep)
    return s


def write_index(mapped: list[dict], latex_out: Path | None = None):
    CHAT_DIR.mkdir(exist_ok=True)
    md_path = CHAT_DIR / "index.md"

    lines = [
        "# Chat Session Index\n",
        "\n",
        "Session: `f23f85b0-55e2-40c3-aa23-a66a258f1d9c`  \n",
        "Source: `~/.claude/projects/-Users-nialloleary/<session>.jsonl`  \n",
        "Generated by: `scripts/chat_index.py`  \n",
        "\n",
        "Each row: one real user prompt → nearest git commit that resulted from it.\n",
        "\n",
        "| # | Timestamp | Prompt | Commit | Message |\n",
        "|---|-----------|--------|--------|---------|\n",
    ]
    for i, m in enumerate(mapped):
        c = m["commit"]
        sha = f"`{c['short']}`" if c else "—"
        msg = escape_md(c["msg"][:50]) if c else "—"
        text = escape_md(m["text"][:80])
        lines.append(f"| {i+1} | {m['ts']} | {text} | {sha} | {msg} |\n")

    md_path.write_text("".join(lines))
    print(f"  wrote {len(mapped)} entries → {md_path}")

    # LaTeX table
    if latex_out:
        tex_lines = [
            "% Auto-generated by scripts/chat_index.py -- do not edit\n",
            "\\begin{longtable}{rp{4cm}p{5cm}ll}\n",
            "\\caption{Chat session index: user prompts mapped to git commits.}\n",
            "\\label{tab:chat}\\\\\n",
            "\\toprule\n",
            "\\# & Timestamp & Prompt & Commit & Message \\\\\n",
            "\\midrule\n",
            "\\endfirsthead\n",
            "\\toprule\n",
            "\\# & Timestamp & Prompt & Commit & Message \\\\\n",
            "\\midrule\n",
            "\\endhead\n",
            "\\midrule\\multicolumn{5}{r}{\\small\\itshape continued\\ldots}\n",
            "\\endfoot\n",
            "\\bottomrule\n",
            "\\endlastfoot\n",
        ]
        for i, m in enumerate(mapped):
            c = m["commit"]
            sha   = f"\\texttt{{{c['short']}}}" if c else "---"
            msg   = escape_tex(c["msg"][:40]) if c else "---"
            text  = escape_tex(m["text"][:70])
            ts    = m["ts"].replace("T", " ")
            tex_lines.append(
                f"{i+1} & \\small {ts} & \\small {text} & {sha} & \\small {msg} \\\\\n"
            )
        tex_lines.append("\\end{longtable}\n")
        latex_out.parent.mkdir(exist_ok=True)
        latex_out.write_text("".join(tex_lines))
        print(f"  wrote LaTeX → {latex_out}")


def main():
    latex_out = None
    for i, arg in enumerate(sys.argv[1:]):
        if arg == "--latex-out" and i + 1 < len(sys.argv) - 1:
            latex_out = Path(sys.argv[i + 2])

    commits = load_commits()
    prompts = load_prompts()
    mapped  = map_to_commits(prompts, commits)

    # Deduplicate: keep only prompts where text is meaningful
    seen = set()
    deduped = []
    for m in mapped:
        key = m["text"][:50]
        if key not in seen:
            seen.add(key)
            deduped.append(m)

    print(f"  {len(deduped)} unique prompts from {len(prompts)} total")
    write_index(deduped, latex_out=latex_out)


if __name__ == "__main__":
    main()
