#!/usr/bin/env python3
"""
Generate results/reference_times.md and paper/reference_times.tex from
results/pd_proteins_stream.jsonl, attaching commit provenance to each row.

Provenance rules:
  - data_commit: the commit that added the stream file to git (git log --follow)
  - code_commit: the last non-[story] commit whose author date precedes the
    row's run timestamp (i.e. the code state at run launch)

Usage:
    python scripts/reference_times.py
"""

import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

REPO   = Path(__file__).parent.parent
STREAM = REPO / "results" / "pd_proteins_stream.jsonl"
MD_OUT = REPO / "results" / "reference_times.md"
TEX_OUT = REPO / "paper" / "reference_times.tex"


def git(*args) -> str:
    return subprocess.check_output(["git"] + list(args), cwd=REPO, text=True).strip()


def data_commit() -> str:
    out = git("log", "--follow", "--format=%h", "--", str(STREAM.relative_to(REPO)))
    return out.splitlines()[-1] if out else "—"


def load_commits() -> list[tuple[datetime, str, str]]:
    out = git("log", "--format=%h|%aI|%s")
    commits = []
    for line in out.splitlines():
        sha, iso, msg = line.split("|", 2)
        if msg.startswith("[story]"):
            continue
        commits.append((datetime.fromisoformat(iso), sha, msg))
    return sorted(commits)


def code_commit_at(ts: datetime, commits) -> str:
    best = "—"
    for cdt, sha, _ in commits:
        if cdt <= ts:
            best = sha
        else:
            break
    return best


def load_rows() -> list[dict]:
    rows = []
    for line in STREAM.read_text().splitlines():
        if line.strip():
            rows.append(json.loads(line))
    return rows


def main():
    rows = load_rows()
    commits = load_commits()
    dc = data_commit()

    for r in rows:
        ts = datetime.fromisoformat(r["ts"].replace("Z", "+00:00"))
        r["_ts"] = ts
        r["_code_commit"] = code_commit_at(ts, commits)
        r["_data_commit"] = dc

    # ── markdown ──
    md = [
        "# Reference Wall-Clock Times — A100 40GB\n\n",
        "Auto-generated by `scripts/reference_times.py` from "
        "`results/pd_proteins_stream.jsonl`.\n",
        "Each row carries two commits: the code state at run launch and the "
        "commit that committed the data.\n\n",
        "| # | Method | Assay | L | N | wall_s | var/s | rho | Run ts (UTC) | Code @ run | Data commit |\n",
        "|---|--------|-------|--:|--:|-------:|------:|----:|--------------|-----------|-------------|\n",
    ]
    for i, r in enumerate(rows, 1):
        md.append(
            f"| {i} | {r['method']} | {r['assay_id']} | {r['sequence_length']} "
            f"| {r['n_variants']} | {r['wall_s']:.3f} | {r['variants_per_s']:.1f} "
            f"| {r['spearman_rho']:+.3f} | {r['_ts'].strftime('%H:%M:%S')} "
            f"| `{r['_code_commit']}` | `{r['_data_commit']}` |\n"
        )
    md.append(
        "\nHardware: NVIDIA A100-SXM4-40GB (Modal). Model: esm2_t33_650M_UR50D fp16.\n"
        "Integrity at run: fair-esm @ 2b369911 (31/31 CLEAN), transformers 4.44.0 "
        "(3/3 SHA256 CLEAN), bridge rho=+0.999973.\n"
    )
    MD_OUT.write_text("".join(md))
    print(f"  wrote {len(rows)} rows -> {MD_OUT}")

    # ── LaTeX ──
    tex = [
        "% Auto-generated by scripts/reference_times.py -- do not edit\n",
        "\\begin{longtable}{rllrrrrl}\n",
        "\\caption{Reference wall-clock times (A100 40GB) with commit provenance.}\n",
        "\\label{tab:reftimes}\\\\\n",
        "\\toprule\n",
        "\\# & Method & Assay & $L$ & wall (s) & var/s & $\\rho$ & Code@run \\\\\n",
        "\\midrule\n\\endfirsthead\n\\toprule\n",
        "\\# & Method & Assay & $L$ & wall (s) & var/s & $\\rho$ & Code@run \\\\\n",
        "\\midrule\n\\endhead\n\\bottomrule\n\\endlastfoot\n",
    ]
    for i, r in enumerate(rows, 1):
        assay = r["assay_id"].split("_")[0]
        method = r["method"].replace("_", "\\_")
        tex.append(
            f"{i} & \\texttt{{{method}}} & {assay} & {r['sequence_length']} "
            f"& {r['wall_s']:.3f} & {r['variants_per_s']:.1f} "
            f"& ${r['spearman_rho']:+.3f}$ & \\texttt{{{r['_code_commit']}}} \\\\\n"
        )
    tex.append("\\end{longtable}\n")
    TEX_OUT.write_text("".join(tex))
    print(f"  wrote LaTeX -> {TEX_OUT}")


if __name__ == "__main__":
    main()
